- src/icplaunchpad_backend/src/lib.rs
1. Stable memory implementation for storing canister ids is done.
2. Function, get all canister ids is also done.
> Stable Memory Implemented

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/lib.rs
- src/icplaunchpad_backend/src/state_handler.rs
implement stable memory for index canister id and get  index_canister_id's and ledger_canister_id in one function
> implement stable memory for index canister id

- Cargo.lock
- download_latest_icp_ledger.sh
- src/ic_asset_handler/Cargo.toml
- src/ic_asset_handler/src/store.rs
- src/icplaunchpad_backend/Cargo.toml
- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/lib.rs
- src/icplaunchpad_backend/src/state_handler.rs
- transfer_test.sh
- Changed the canisteridwrapper struct in such a way that, it also stores image id 
- Deleted imageidwrapper since it's unnecessary (storing canister content in canisteridwrapper)
- Changed implementation of upload_image in such a way that, stores image id, with corresponding ledger id
- Changed get image ids in such a way that, it returns the corresponding ledger id also.
> Linking upload_image with ledger id

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/lib.rs
- src/icplaunchpad_backend/src/state_handler.rs
1. -Made different functions for token image uploads and profile image uploads
2. - Made appropriate get image id functions for both
3. - Linked image id of token with it's ledger id.
4. -Linked profile id of user with it's principal.
> Token Image and Profile Image uploads to Asset Canister

- src/icplaunchpad_frontend/src/Pages/VerifyToken/Tabs/AdditionalInfoTab.jsx
- src/icplaunchpad_frontend/src/common/AnimationButton.jsx
- src/icplaunchpad_frontend/src/common/UserValidation.js
- src/icplaunchpad_frontend/src/components/Header/Header.jsx
- src/icplaunchpad_frontend/src/components/Modals/CreateUser.jsx
- src/icplaunchpad_frontend/src/components/Modals/UpdateUser.jsx
> Update user fix

- Scripts/transfer.sh
- deploy.sh
- deploy_main.sh
- deployicpledger.sh
- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/lib.rs
- src/icplaunchpad_backend/src/transaction.rs
-Converted the system time return from nano seconds to seconds to match data from frontend
-Get APIs are working correctly according to start time and end time.
> Altered Logic of GetUpcomingSale

- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- Updating Profile Picture of user has changed with handling the new image id.
> Profile Image Upload

- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- Fixed the logic for Upcoming Sales now, back to converting.
> Fixed Logic for Upcoming, Active and Successful Sales

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- Added a new API: get_user_sale_params on querying, returns the sale parameters or the sales created by that particular user.
> get_user_sale_params api added

- deps/pulled.json
- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/transaction.rs
- src/icplaunchpad_backend/src/types.rs
- Buy_tokens function is working successfully.
- Takes in amount of tokens, from principal and Ledger Canister id.
> Payment Function Working Successfully

- src/icplaunchpad_backend/src/api_update.rs
- Fixed Start Time and End time issue.
> Update Sale Params Fix

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
> get all sales API

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- Altered get_tokens_info API in such a way that, now it returns ongoing sales of tokens and also which have entered sale info.
> altered getokensinfo API

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/params.rs
- src/icplaunchpad_backend/src/transaction.rs
> Sell API added

- deps/pulled.json
- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/lib.rs
- src/icplaunchpad_frontend/vite.config.js
> Query file

- src/icplaunchpad_frontend/src/Pages/Project/project.jsx
- src/icplaunchpad_frontend/src/components/Header/Header.jsx
- src/icplaunchpad_frontend/src/components/Modals/ProfileCard.jsx
> ICP Balance Show

- deps/init.json
- src/icplaunchpad_frontend/src/Pages/CreatePreLaunch.jsx
- src/icplaunchpad_frontend/src/Pages/Project/project.jsx
- src/icplaunchpad_frontend/src/Pages/VerifyToken/Tabs/ReviewInfoTab.jsx
- src/icplaunchpad_frontend/src/Pages/VerifyToken/VerifyToken.jsx
- src/icplaunchpad_frontend/src/common/UserValidation.js
> verify token fixed

- deploy.sh
- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
-get_user_token_upcoming_info and get_user_token_successful_info added- for the returning of fixed initial total supply.
> NEW APIs- get_user_token_upcoming_info and get_user_token_successful_info

- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/types.rs
- Returning initial total supply in Upcoming Sales and Successful Sales API
> Changes in Upcoming Sales and Successful Sales API

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/lib.rs
- Exposed trusted origins function for the NFID Identity Kit.
> Trusted Origins is Exposed

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/lib.rs
- Baby Canisters controllers are: Backend Local Canister, Backend Mainnet Canister, Caller.
> Controllers of Baby Canisters Updated.

- src/icplaunchpad_backend/src/api_update.rs
- New API called Deposit_cycles_to_canister to top up Baby Canisters.
> API to deposit cycles to Baby Canisters

- deploy.sh
- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_update.rs
- changed the path from ic to local for local deployment for now.
> Local deploy.sh script update

- src/icplaunchpad_frontend/src/Pages/Home.jsx
- src/icplaunchpad_frontend/src/Pages/Project/project.jsx
- src/icplaunchpad_frontend/src/components/LaunchACoin/Clients.jsx
- src/icplaunchpad_frontend/src/components/LaunchACoin/FundedProjects.jsx
> Newfix error

- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/lib.rs
- src/icplaunchpad_backend/src/transaction.rs
- src/icplaunchpad_backend/src/types.rs
- Hearbeat functions implemented, testing is pending.
- Post sale logic functions implemented, testing is pending.
> Post Sale Logic for Fairlaunch with Hearbeats

- src/icplaunchpad_backend/src/api_update.rs
> Local Path change of wasm

- deploy.sh
- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/heartbeat.rs
- src/icplaunchpad_backend/src/lib.rs
- src/icplaunchpad_backend/src/params.rs
- src/icplaunchpad_backend/src/state_handler.rs
- src/icplaunchpad_backend/src/transaction.rs
- src/icplaunchpad_backend/src/types.rs
- **create_token** has the following changes:
1.  Minter principal is now changed to aaaaa-aa (blackhole principal)
- **create_sale** has the following changes:
1. We're using another struct for input params of user, and we're using saleparams struct to store and calculate liquidity tokens, fee to be taken. The number of tokens to be taken for approval is returned when create_sale is executed
> Sale Logic Implemented for Fair Launch

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/types.rs
- Update and Query functions fixed of Sale according to new parameters.
> get and update sale functions fix

- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/task_scheduler.rs
- src/icplaunchpad_backend/src/transaction.rs
- src/icplaunchpad_backend/src/types.rs
- Logic changes in task scheduler function
> Task Scheduler Logic Changes

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_update.rs
- Import token now checks whether the imported token ledger id already exists
- Error Handling in Import token
> Import token error handling

- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/transaction.rs
- src/icplaunchpad_backend/src/types.rs
- Error Handling in api_query.rs file
- Improved Robustness and cleaner logic done in query APIs
> Error Handling in api_query.rs

- src/icplaunchpad_backend/src/task_scheduler.rs
- src/icplaunchpad_backend/src/transaction.rs
- Transaction logic changed in buy_tokens, now contributions are stored
- Distribute tokens is now working, by distributing tokens to the contributors.
> Token Distributions are working now

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/state_handler.rs
- Fixed Index canister id returned as an empty string.
> Index Canister id fix in get_tokens_info and get_user_tokens_info

- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/types.rs
- getusertokensinfo function now return imported token information along with tokens created using create_token function.
- gettokeninfo returns active sale token info of both created tokens and imported tokens.
- imported tokens now works with an optional index canister id, if entered then imported directly, if not index canister is installed for the ledger canister id entered.
> getusertokensinfo and gettokensinfo functions now return 

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/transaction.rs
- Commented out validation of existing ledger ids for import token function for testing for now.
> Commented out validation for import token for testing

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/task_scheduler.rs
- src/icplaunchpad_backend/src/transaction.rs
- Fee functions added for tax on tokens, and tax on funds raised for a sale.
- Timer functions are altered accordingly such that, fee functions are called only when token distribution take place.
> Fee functions and Timer functions logic altered accordingly

- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- log statements added in files for better debugging.
> Debug Statements/ Log Statements Added

- Cargo.lock
- src/icplaunchpad_backend/icplaunchpad_backend.did
- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- get_token_image_id function now takes in ledger canister id as input instead of the user principal and retrieves the image id stored.
> get token image id now takes ledger canister id as input

- src/icplaunchpad_backend/src/api_query.rs
- src/icplaunchpad_backend/src/api_update.rs
- src/icplaunchpad_backend/src/lib.rs
- src/icplaunchpad_backend/src/state_handler.rs
- src/icplaunchpad_backend/src/task_scheduler.rs
- src/icplaunchpad_backend/src/transaction.rs
- src/icplaunchpad_backend/src/types.rs
- test_fairlaunch.sh
- Anonymous Guard on all exported functions.
> Anonymous Guard on functions exported
